services:
  app:
    build: .
    container_name: golearn-container
    volumes:
      - .:/app
    ports:
      # ホストの8081ポートをコンテナの8080ポートにマッピング
      # (8080は他のプロセスで使用中のため)
      - "8080:8080"
    command: tail -f /dev/null
    environment:
      - CGO_ENABLED=1
